/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nasa;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import static java.lang.StrictMath.abs;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Oscar
 */
public class Map extends javax.swing.JFrame {

    /**
     * Creates new form Map
     */
    public Map() {
        initComponents();
        this.setSize(1216,650);
        this.setTitle("Nacaome Aeronautics and Space Administration");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InsertCoordinates = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CY = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        CX = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        mainScreen = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        button_add = new javax.swing.JLabel();
        button_edit = new javax.swing.JLabel();
        button_delete = new javax.swing.JLabel();
        map = new javax.swing.JLabel();

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Star Jedi", 1, 18)); // NOI18N
        jLabel1.setText("insert coordinates");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 20, 250, 50);

        jLabel3.setFont(new java.awt.Font("Swis721 Blk BT", 1, 48)); // NOI18N
        jLabel3.setText(",");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(150, 80, 20, 60);

        jLabel4.setFont(new java.awt.Font("Swis721 Blk BT", 1, 48)); // NOI18N
        jLabel4.setText("[");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 80, 30, 60);

        CY.setFont(new java.awt.Font("Star Jedi", 1, 18)); // NOI18N
        CY.setModel(new javax.swing.SpinnerNumberModel(80, 80, 370, 1));
        jPanel1.add(CY);
        CY.setBounds(180, 100, 60, 30);

        jLabel5.setFont(new java.awt.Font("Swis721 Blk BT", 1, 48)); // NOI18N
        jLabel5.setText("]");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(250, 80, 30, 60);

        CX.setFont(new java.awt.Font("Star Jedi", 1, 18)); // NOI18N
        CX.setModel(new javax.swing.SpinnerNumberModel(80, 80, 630, 1));
        jPanel1.add(CX);
        CX.setBounds(80, 100, 60, 30);

        jButton1.setFont(new java.awt.Font("Star Jedi", 1, 12)); // NOI18N
        jButton1.setText("accept");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(100, 150, 110, 30);

        InsertCoordinates.getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        mainScreen.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Star Jedi", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("jedi navigation system");
        mainScreen.add(jLabel2);
        jLabel2.setBounds(200, 480, 534, 50);

        button_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nasa/b_add.png"))); // NOI18N
        button_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_addMouseClicked(evt);
            }
        });
        mainScreen.add(button_add);
        button_add.setBounds(810, 200, 370, 70);

        button_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nasa/b_edit.png"))); // NOI18N
        mainScreen.add(button_edit);
        button_edit.setBounds(810, 280, 369, 74);

        button_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nasa/b_delete.png"))); // NOI18N
        mainScreen.add(button_delete);
        button_delete.setBounds(810, 360, 370, 70);

        map.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nasa/screen.png"))); // NOI18N
        mainScreen.add(map);
        map.setBounds(0, -10, 1200, 640);

        getContentPane().add(mainScreen);
        mainScreen.setBounds(0, 0, 1200, 630);

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    public Icon imageToIcon(Image image){
        ImageIcon imgIcon = new ImageIcon(image);
        Icon iconReturn=(Icon)imgIcon;
        return iconReturn;
    }
    
    private void button_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_addMouseClicked
       JLabel newPlanet = new JLabel();
       
       // COORDINATE
       
       newPlanet.setLocation(0,0);
       newPlanet.setSize(100,100);
       
       String planet = "C:\\Users\\Oscar\\Documents\\NetBeansProjects\\NASA\\src\\nasa\\";

       
       if(usedPlanets.isEmpty()){
           planet += "p0.png";
           usedPlanets.add("p0.png");
       }
       
       else{
           planet += ("p" + usedPlanets.size() + ".png");
           usedPlanets.add("p" + usedPlanets.size() + ".png");
       }
       
       BufferedImage image = null;
            File f = new File(planet);
            try {
                image = ImageIO.read(f);
            } catch (IOException ex) {
                System.out.println("");
            }
            
      newPlanet.setIcon(imageToIcon(image));
      map.add(newPlanet);
      newPlanet.setVisible(true);
      this.repaint();
    }//GEN-LAST:event_button_addMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       // COORDINATES
       int x = (int)CX.getValue();
       int y = (int)CY.getValue();
       
       boolean acceptX = false;
       boolean acceptY = false;
       
       if(coordinates.isEmpty()){
           coordinates.add(x);
           coordinates.add(y);
        }
       
       else{
           for(int i = 0; i < coordinates.size(); i++){
               if(i%2 == 0){ // Planeta montado 
                   if(abs(x-(int)coordinates.get(i)) >= 50 ){
                       
                   }
               }
                   
           }
       }
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Map().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner CX;
    private javax.swing.JSpinner CY;
    private javax.swing.JDialog InsertCoordinates;
    private javax.swing.JLabel button_add;
    private javax.swing.JLabel button_delete;
    private javax.swing.JLabel button_edit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel mainScreen;
    private javax.swing.JLabel map;
    // End of variables declaration//GEN-END:variables
    ArrayList <String> usedPlanets = new ArrayList();
    ArrayList coordinates = new ArrayList();

}
